### ISSUE TITLE
Wasync 2.0.0 not compatible with Android.

### ISSUE THREAD

**Issue by phemphill** [Atmosphere/wasync#120]
I tried to use the 2.0.0 release of Wasync in an android project and it failed to create a socket due to an exception. After a little bit of investigation the problem appears to be with Async-http-client. Please see the issue: https://github.com/AsyncHttpClient/async-http-client/issues/783

The version of ahc in master of wasync seems to be updated to a version of ahc that includes the fix for this issue. I am however logging this issue at least for documentation sake.

**Comment by jfarcand** [comment]
@phemphill Thanks for reporting!

**Comment by ricardojlrufino** [comment]
Same problem:
`Caused by: java.lang.ClassNotFoundException: Didn't find class "sun.security.util.HostnameChecker"`

**Comment by ricardojlrufino** [comment]
Workaround 
`System.setProperty("com.ning.http.client.AsyncHttpClientConfig.acceptAnyCertificate", "true");`

**Comment by jfarcand** [comment]
@ricardojlrufino Just update to a newer version of `async-http-client`. The bug was in there.

**Comment by deviant-studio** [comment]
Android lib still doesnt work. I tried to upgrade async-http-client to the latest available version:
 ```
compile 'com.ning:async-http-client:+'
compile ('org.atmosphere:wasync:2.+') {
        exclude group: 'com.ning', module: 'async-http-client'
}
```
and got this error when connecting
```
java.lang.NoClassDefFoundError: com/ning/http/util/AsyncHttpProviderUtils
Unable to connect: java.lang.NoClassDefFoundError: com/ning/http/util/AsyncHttpProviderUtils
```

**Comment by slandelle** [comment]
@deviant-studio Your issue is that AHC is compiled against JDK7 and you're running on an Android version that doesn't support it (older than KitKat).

**Comment by deviant-studio** [comment]
But there is still a lot of devices with ICS and JellyBean (about 55% of all devices). Is there some workaround for old OS versions?

**Comment by slandelle** [comment]
Disclaimer: I'm AHC main developer, the library under which wasync is built. Android compatibility is not a concern for me, I couldn't care less. But I'm not part of Atmosphere or wasync, so my opinion and choices are my own.

You could either use old AHC/wasync versions that are built with JDK6 (with security issues that forced me to upgrade to JDK7).
Or, you could contract with [Async.io](http://async-io.org/), the company behind Atmosphere (once again, I'm not related) so that they invest in old Android versions compatibility.
